name: 🐛 Bug Report
description: Create a report to help us improve Claude Good Hooks
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out the form below with as much detail as possible.

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Claude Good Hooks are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is affected?
      options:
        - claude-good-hooks-cli
        - claude-good-hooks-types
        - claude-good-hooks-factories
        - claude-good-hooks-template-hook
        - claude-good-hooks-examples
        - dirty-hook
        - Not sure
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "When I run... I expected... but instead..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Install package with `pnpm install @sammons/claude-good-hooks`
        2. Create hook with `...`
        3. Run `...`
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happened
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Any error messages or logs
      render: shell
      placeholder: |
        Paste error logs here...

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      render: yaml
      placeholder: |
        OS: macOS 14.0
        Node: v20.10.0
        pnpm: 9.0.0
        Claude Code: v2.1.0
        Shell: zsh
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Hook configuration files
        - Custom setup details
        - Workarounds you've tried
        - Related issues

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues
          required: true
        - label: I have included all relevant information
          required: true
        - label: I can reproduce this issue consistently
          required: true