name: Bundle Size Check

on:
  push:
    branches: [main]
    paths:
      - 'packages/landing-page/**'
  pull_request:
    branches: [main]
    paths:
      - 'packages/landing-page/**'

jobs:
  bundle-size-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'packages/landing-page/package-lock.json'
          
      - name: Install dependencies
        working-directory: packages/landing-page
        run: npm ci
        
      - name: Build and check bundle size
        working-directory: packages/landing-page
        run: npm run build:check
        
      - name: Generate bundle report
        working-directory: packages/landing-page
        run: npm run build:analyze > bundle-report.txt
        
      - name: Upload bundle report
        uses: actions/upload-artifact@v4
        with:
          name: bundle-report
          path: packages/landing-page/bundle-report.txt
          
      - name: Comment bundle size on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Read bundle report
            const reportPath = path.join('packages', 'landing-page', 'bundle-report.txt');
            const report = fs.readFileSync(reportPath, 'utf8');
            
            // Post comment on PR
            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;
            
            const comment = `## 📦 Bundle Size Report
            
            \`\`\`
            ${report}
            \`\`\`
            
            *This report shows the current bundle sizes and budget status.*
            `;
            
            github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: comment
            });