version: '3.8'

services:
  smoke-tests:
    build:
      context: ../../  # Build from the monorepo root
      dockerfile: ./packages/claude-good-hooks-smoke-tests/Dockerfile
    container_name: claude-good-hooks-smoke-tests
    volumes:
      # Mount source code for development workflow
      - ../../packages/claude-good-hooks-types:/app/packages/claude-good-hooks-types
      - ../../packages/claude-good-hooks-cli:/app/packages/claude-good-hooks-cli  
      - ../../packages/claude-good-hooks-smoke-tests:/app/packages/claude-good-hooks-smoke-tests
      # Mount package files for dependency changes
      - ../../package.json:/app/package.json
      - ../../pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      - ../../pnpm-lock.yaml:/app/pnpm-lock.yaml
    working_dir: /app/packages/claude-good-hooks-smoke-tests
    environment:
      - NODE_ENV=test
      - CI=true
    # Override default command for different operations
    command: pnpm run smoke
    
  # Service for development with watch mode
  smoke-tests-dev:
    build:
      context: ../../
      dockerfile: ./packages/claude-good-hooks-smoke-tests/Dockerfile
    container_name: claude-good-hooks-smoke-tests-dev
    volumes:
      - ../../packages/claude-good-hooks-types:/app/packages/claude-good-hooks-types
      - ../../packages/claude-good-hooks-cli:/app/packages/claude-good-hooks-cli
      - ../../packages/claude-good-hooks-smoke-tests:/app/packages/claude-good-hooks-smoke-tests
      - ../../package.json:/app/package.json
      - ../../pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      - ../../pnpm-lock.yaml:/app/pnpm-lock.yaml
    working_dir: /app/packages/claude-good-hooks-smoke-tests
    environment:
      - NODE_ENV=test
    command: pnpm test:watch
    stdin_open: true
    tty: true

  # Service for building only (useful for CI/testing the build)
  smoke-tests-build:
    build:
      context: ../../
      dockerfile: ./packages/claude-good-hooks-smoke-tests/Dockerfile
    container_name: claude-good-hooks-smoke-tests-build
    volumes:
      - ../../packages/claude-good-hooks-types:/app/packages/claude-good-hooks-types
      - ../../packages/claude-good-hooks-cli:/app/packages/claude-good-hooks-cli
      - ../../packages/claude-good-hooks-smoke-tests:/app/packages/claude-good-hooks-smoke-tests
    working_dir: /app/packages/claude-good-hooks-smoke-tests
    environment:
      - NODE_ENV=test
    command: pnpm build